### PR TITLE
fix(transform-fast-rest): rest parameters references with closures

### LINKED ISSUE #797: [Transpiling] Rest parameters doesn't work with non-arrow function closures
Hello there!

I've encountered a bug with the transpiling of the rest parameters.

Pratically the transpiler with something like this:
```js
export function brokenArgsRest(fn, ...args) {
  return function () {
    fn(...args);
  };
}
```

Will treat the arguments object in the wrong way:
```js
function brokenArgsRest(fn) {
  return function () {
    fn.apply(void 0, [].slice.call(arguments, 1));
  };
}
```

I've created a minimal repro here --> https://github.com/gdorsi/microbundle-args-rest-issue

### PR DESCRIPTION
**Pull request by gdorsi**
closes #797

### CODE REVIEW

File: src/lib/transform-fast-rest.js [hunk 1]
```diff
@@ -43,7 +43,12 @@ export default function fastRestTransform({ template, types: t }) {
 					func.arrowFunctionToExpression();
 				}
 
-				if (binding.constant && binding.referencePaths.length === 1) {
+				if (
+					binding.constant &&
+					binding.referencePaths.length === 1 &&
+					// arguments access requires the same function scope
+					getParentFunction(binding.referencePaths[0], t) === func
```
Comment (developit) [inline src/lib/transform-fast-rest.js:50]: nit: there's a builtin for this (though see my other comment for why you might actually have the better approach here!)

```suggestion
					binding.referencePaths[0].getFunctionParent() === func
```

File: src/lib/transform-fast-rest.js [hunk 2]
```diff
@@ -88,3 +93,11 @@ export default function fastRestTransform({ template, types: t }) {
 		},
 	};
 }
+
+function getParentFunction(node, t) {
+	while ((node = node.parentPath)) {
+		if (t.isFunction(node)) {
```
Comment (developit) [inline src/lib/transform-fast-rest.js:99]: Arrow functions can access `arguments` from the enclosing scope, so we could allow them in the tree here:

```suggestion
		if (t.isFunction(node) && !t.isArrowFunctionExpression(node)) {
```

**Review by developit — COMMENTED** [review]
This is great! Curious to get your thoughts on the arrow function bit, otherwise this looks ready to go.

File: src/lib/transform-fast-rest.js (hunk 1 above)
Comment (gdorsi) [reply src/lib/transform-fast-rest.js:50]: aww, that's nice!

File: src/lib/transform-fast-rest.js (hunk 2 above)
Comment (gdorsi) [reply src/lib/transform-fast-rest.js:99]: I thought about that, but if the rest parameters transformation is applied with the same criteria of the arrow function transformation there would be no gain in terms of bundlesize.

Instead if the `[].slice.call` is moved in the root function scope it would be cached in some cases.

Comment (gdorsi) [reply src/lib/transform-fast-rest.js]: I've made the change and without the arrow function check the bundle size of the test case seems smaller:

With the arrow function check:
```
157 B: parameters-rest-closure.js.gz
115 B: parameters-rest-closure.js.br
165 B: parameters-rest-closure.esm.js.gz
124 B: parameters-rest-closure.esm.js.br
247 B: parameters-rest-closure.umd.js.gz
189 B: parameters-rest-closure.umd.js.br
```

With getFunctionParent
```
146 B: parameters-rest-closure.js.gz
106 B: parameters-rest-closure.js.br
153 B: parameters-rest-closure.esm.js.gz
113 B: parameters-rest-closure.esm.js.br
238 B: parameters-rest-closure.umd.js.gz
177 B: parameters-rest-closure.umd.js.br
```

**Review by developit — APPROVED** [review]
LGTM!

File: src/lib/transform-fast-rest.js (hunk 2 above)
Comment (developit) [reply src/lib/transform-fast-rest.js]: makes sense from a Gzip perspective (repetition is essentially free), just there's a runtime cost associated with materializing `arguments` via slice() where it wouldn't otherwise be necessary.
